// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7A7SGWAMohk6KaABV9ty4FXt7acVW0E0',
    appId: '1:1084609560881:android:5845161315ff7cccbff010',
    messagingSenderId: '1084609560881',
    projectId: 'muqrnapp',
    storageBucket: 'muqrnapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLigBE0WnQhon_ZEtIGPZ1jNUP4Lkou0',
    appId: '1:1084609560881:ios:3e2e870cac8ebe03bff010',
    messagingSenderId: '1084609560881',
    projectId: 'muqrnapp',
    storageBucket: 'muqrnapp.firebasestorage.app',
    androidClientId: '1084609560881-llhfnbsfj734bc02rv734uo71g5t8hgi.apps.googleusercontent.com',
    iosClientId: '1084609560881-v7gp06co8vrlf5eoh2ivoi4osm80duk0.apps.googleusercontent.com',
    iosBundleId: 'com.app.muqrn',
  );

}